### PR TITLE
(Singular) Post Page

### PR DESCRIPTION
**Pull request by jd-lo**
A view for each post, with a somewhat styled page. Partial implementation as several features are waiting for back-end support

- [x] Add dynamic routing to posts
- [x] Have post-proper
- [x] Have author
- [x] Re-route on card click
- [x] Comments appear
- [x] Swanky comment toggle animation
- [x] Comments are scrollable
- [x] Comments are paginated -- implementation pending on back-end support  

https://user-images.githubusercontent.com/90064709/226818967-7a6f9375-f038-4018-bd58-df34e22e46ba.mp4

### CODE REVIEW

**Comment by jd-lo** [comment]
There's a really big bug atm that I can't resolve yet. Occasionally, when routing from a card to its respective page, the post properly renders the content before it's retrieved from the server, resulting in undefined attributes. This can happen (or not) to any post, and when it does, it completely bricks the routing (Manage, homepage etc, will no longer load correctly.)

**Comment by jd-lo** [comment]
We had to make some back-end changes here to support this (which broke the social page), so the changes most recent changes are based on the restructured back-end branch (If you want the data I used for preliminary testing since making your own data is kinda time-consuming and adding comments aren't supported, you can check them out in `Jonathan's test branch` -- which is just the restructured back-end w/ data

**Review by geofferb — APPROVED** [review]
All good, following and likes needs to be implemented

**Comment by geofferb** [comment]
Closes CMPUT404W23T05/CMPUT404-project-socialdistribution#33

**Pull request merged**
