### PR TITLE
Posts view page

### PR DESCRIPTION
**Pull request by kirat21**

### CODE REVIEW

**Review by jd-lo — DISMISSED** [review]
`Browse.vue`: postSections should be the unique time date of publish per post as seen on figma.

e.g) With the exception of "today," should follow date format (i.e 02/12/16 or whatever). The current implementation results in too lopsided of a display (For every 2 posts made "today," there could be a hundred in "One month ago".

There are too many `<br>` elements. Remove them and style them with CSS.

The component for cards should be imported from `../components/RevisedCard.vue`, not `../components/PostCard.vue` (The import might be the only change required)

Styles for the cards should **not** be set in `Browse.vue,` change them within the Card component itself.

**Comment by jd-lo** [comment]
Not something to worry about for now, but all assets that have been added for this feature will eventually need to be replaced with SVGs, not PNGs.

**Comment by jd-lo** [comment]
I can't load any of the posts from the server on the browse page.

**Review by geofferb — APPROVED** [review]
works!

**Pull request merged**
